### ISSUE TITLE
Sidekiq 4.0

### ISSUE THREAD

**Issue by jnylen** [ixti/sidekiq-throttled#1]
Hi,
Amazing gem you got here. Is it possible for you to look into moving it over to allow Sidekiq 4.0?
You need to drop the requirement of celluloid though.

**Comment by ixti** [comment]
Well, `sidekiq-throttled` does not depend on celluloid directly.
And yes, I'm thinking of making it sidekiq 4.0 friendly. In fact,
we will support both 3.x and 4.x sidekiq branches.

Stay tuned! ;))

**Comment by badlamer** [comment]
+1

**Comment by jnylen** [comment]
Any ETA on this @ixti ?

**Comment by thatdom** [comment]
Thanks for great gem, any news on Sidekiq 4 support?

**Comment by VishalRam** [comment]
+1

**Comment by jcran** [comment]
+1

**Comment by ChaoticBoredom** [comment]
This looks awesome, appears to combine the utility of two different gems we're using. Supporting Sidekiq 4.0 would definitely be the topper.

**Comment by divoxx** [comment]
+1

**Comment by jnylen** [comment]
Any ETA on this @ixti?

**Comment by ixti** [comment]
Released with `0.3.0.pre`. Please report issues if any. Will release `0.3.0` after a week.
