### ISSUE TITLE
Ruby 3.0 compatibility

### ISSUE THREAD

**Issue by mattbrictson** [ixti/sidekiq-throttled#101]
Why was compatibility with Ruby 3.0 dropped in sidekiq-throttled 0.14.1 (74dbf05a5a962531c14e107a61d943daf337c8e2)? Are there plans to add it back?

**Comment by airtasker-candidate-review** [comment]
Yeah we’ve been running sidekiq-throttled in production with Ruby 3 for a while and we can’t update this dependency now because of this change.

**Comment by NikoRoberts** [comment]
Yeah we’ve been running sidekiq-throttled in production with Ruby 3 for a while and we can’t update this dependency now because of this change.

**Comment by anark** [comment]
This is blocking us from upgrading to Ruby 3.  It seems like @ybiquitous has a ruby-3 fork https://github.com/ybiquitous/sidekiq-throttled/tree/ruby-3, I wonder if they would make a PR.

Was there a particular reason ruby-3 was removed?  Can ruby 3 support be added?

**Comment by ybiquitous** [comment]
@anark 

> This is blocking us from upgrading to Ruby 3.

Yes, me too.
I've created the patch and tested it on ybiquitous/sidekiq-throttled#1, but the test failed. I don't know the failure reason. 🤷🏼 

Of course, I can open a pull request for this repo with the insufficient patch if it would help someone.

**Comment by anark** [comment]
Strange, on first look those failures seem to be related to test setup more than actual failures.

Would you be open to opening a PR and me, @ixti or someone from @sensortower can try to finish it up?

**Comment by ybiquitous** [comment]
@anark Thanks! I've opened PR #102!

**Comment by zrod** [comment]
I'd love to give this gem a try but am using ruby 3. I'm also curious to know why ruby 3 was dropped on the last release.
I guess I'll fork it for now, until the PR is merged (hopefully soon), thanks!

**Comment by ilangoldman** [comment]
Hey guys, any chance to get this Issue closed anytime soon? We want to update our project to ruby 3 and this is currently the only dependency that is not ready yet.

**Comment by ybiquitous** [comment]
Unfortunately, the answer is no. 😢 

You can see the CI failures on my fork PR ybiquitous/sidekiq-throttled#1.
(the CI on #102 is not approved...)

**Comment by amrrbakry** [comment]
Our team is also blocked by this. I'm happy to help in any way to speed this up.

**Comment by ixti** [comment]
The fix was merged and shortly will do the release. Gonna merge in the last outstanding pr and will cut the release.
