### ISSUE TITLE
Enhanced queue tab not show "Latency" column

### ISSUE THREAD

**Issue by ArmandoAssuncao** [ixti/sidekiq-throttled#108]
In route `/sidekiq/queues` is show the column "Latency":

![sidekiq_queue](https://user-images.githubusercontent.com/12402128/147998414-7af33aaa-3fbf-4476-a8d3-9b451ccbefbd.png)

But in route `/sidekiq/enhanced-queues` not show:

![sidekiq_queue_enhanced](https://user-images.githubusercontent.com/12402128/147998424-5e0d3ae7-7caf-4bae-b368-92b40d9cf106.png)

tested in v0.15.0

**Comment by ixti** [comment]
Fixed in v1.0.0.alpha
