### ISSUE TITLE
sidekiq_throttle_as doesn't work in inherited classes

### ISSUE THREAD

**Issue by RichardsonWTR** [ixti/sidekiq-throttled#109]
## What's the problem? 
The throttle is not being used in inherited classes. 
I've just noticed this by looking at the sidekiq web interface and realized that there were more jobs running than the defined in the throttle. And the running jobs in the throttle stats were zero.  

Version: 0.15.0

## How to reproduce it? 

Implement a worker base and an inherited one: 

```ruby
class BaseWorker
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker
  sidekiq_throttle_as :my_throttle
end

class ChildWorker < BaseWorker
end
```

Now use your worker and notice that the throttle will always be set to zero (no jobs in the throttle).  
Another way of checking this behavior is to start more workers than the defined.

### Where do I think that the problem is: 

My guess is the problem lives inside the Registry#find_by_class that's used by [Registry#get](https://github.com/sensortower/sidekiq-throttled/blob/1153539421b41b57d6f110fc2743919146e7ba5e/lib/sidekiq/throttled/registry.rb#L107)

Look at some discoveries that I've made in the Rails console: 

```
> Sidekiq::Throttled::Registry.get(BaseWorker) # It returns an object

> Sidekiq::Throttled::Registry.get(ChildWorker) # It returns nil
```

**Comment by ixti** [comment]
For now you can fix this with:

``` ruby
Sidekiq::Throttled.configuration.inherit_strategies = true
```

I will make this default behaviour in the future. But I need to find a solution that will be least confusing. As there are too many edge cases.
