### ISSUE TITLE
Sidekiq 7 Support

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [ixti/sidekiq-throttled#134]
Sidekiq 7 just got released and brought breaking changes.

It would be really great to make `sidekiq-throttled` compatible with Sidekiq 7.

This is the first error I got in CI:

```
NoMethodError: undefined method `error_handlers' for Sidekiq:Module

        Sidekiq.error_handlers << Sidekiq.method(:default_error_handler)
               ^^^^^^^^^^^^^^^
/home/runner/work/rails_app/vendor/bundle/ruby/3.1.0/gems/sidekiq-throttled-0.17.0/lib/sidekiq/throttled/communicator/exception_handler.rb:17:in `<class:Communicator>'
```

I think @mperham is even offering 1:1 pairing sessions to help migrating plugins to Sidekiq 7.0 as per his [Twitter post](https://twitter.com/getajobmike/status/1570530115255439360).

**Comment by OskarEichler** [comment]
+1 🙌🏼

**Comment by OskarEichler** [comment]
@ixti Any news on this? The gem [sidekiq-scheduler](https://github.com/sidekiq-scheduler/sidekiq-scheduler) was recently updated, so now this is the only dependency that prevents us from upgrading to Sidekiq 7. Would be great if you can let us know when you think you'd have time to check the changes - otherwise maybe the community can contribute as well! 🙌🏼

**Comment by ixti** [comment]
@OskarEichler I'm having plenty of things going on in my life right now, and unfortunately don't have much spare time I'd like to dedicate to the gem. Maintainers are always welcomed. And surely, if you will open a PR - I'll be happy to review and merge.

**Comment by droplotus** [comment]
Hey, hope everything is doing fine @ixti , I've seen you've been busy lately and hope things have been settled down!
Are you working on any update so far? :)
Thank you for this btw! Cheers

**Comment by ixti** [comment]
I will try to get this done this or next week.

**Comment by fatkodima** [comment]
Here you go - https://github.com/ixti/sidekiq-throttled/pull/142

**Comment by ixti** [comment]
Thanks to @fatkodima it is resolved now! :D

**Comment by michael-quickmail** [comment]
Hey there @ixti 
Thanks for this gem!
Is there a release planned with this improvement somewhere in the near future ?
Making the gem point to the main Github branch is a bit risky for production applications

**Comment by ixti** [comment]
Yes. I'm planning to finish a couple of cleanups and cut the release soon (this or next week).

**Comment by eric-hu** [comment]
Hi @ixti I think there might have been an issue with the versioning. I see this when I try to upgrade to Sidekiq 7.1.0

```
Bundler could not find compatible versions for gem "sidekiq":
  In snapshot (Gemfile.lock):
    sidekiq (= 7.1.0)
  In Gemfile:
    sidekiq-throttled (>= 0.18.0) was resolved to 0.18.0, which depends on
      sidekiq (~> 6.4)
```

**Comment by ixti** [comment]
I've abandoned all hopes making v0.x.x compatible with Sidekiq 7.0; It will be part of v1.0.0 which I hope to release next week

**Comment by eric-hu** [comment]
Understood, thanks for responding so quickly!

**Comment by remy727** [comment]
Any update on releasing **v1.0.0**?

**Comment by ixti** [comment]
Had a rough couple of weeks. Will work on release this week.

**Comment by pboling** [comment]
@ixti Thanks for working on it! I presume the things keeping the release from realizing are not insignificant, and thus I have a few questions...

1. Would it be helpful for those of us on Sidekiq 7 already to target the main branch and report issues?  I am on latest Sidekiq, and am only now adopting this gem for concurrency and throttling, so I can dog food it.
2. Does it work at least enough to run?
3. Are there any caveats we should be aware of?
