### ISSUE TITLE
Dependency breaking change in redis-prescription

### ISSUE THREAD

**Issue by nicolascian** [ixti/sidekiq-throttled#141]
Dependency breaking change

`redis-prescription` removed the `.read` method:
https://gitlab.com/ixti/redis-prescription/-/commit/c9410a067d9a69bdb06b54447bd5becfa7f8ee42

it's being used here:
https://github.com/ixti/sidekiq-throttled/blob/main/lib/sidekiq/throttled/strategy/concurrency.rb#L23

and here:
https://github.com/ixti/sidekiq-throttled/blob/main/lib/sidekiq/throttled/strategy/threshold.rb#L33

**Comment by ixti** [comment]
Thanks to @fatkodima it is resolved now! :D
