### ISSUE TITLE
migration plan for sidekiq 7

### ISSUE THREAD

**Issue by skyeagle** [ixti/sidekiq-throttled#165]
Hi @ixti 

Thank you for your excellent work on this gem!

What would be a migration plan to upgrade sidekiq from 6 to 7, taking into account that version 1.0.0 that got released recently, drops support for sidekiq 6.x? Should we update this gem to 1.0.0alpha first, which is still compatible?

Thank you!

**Comment by ixti** [comment]
I have dropped the 6.5 support only for cleanup purpose. Will add it back to the matrix, as code should be fully 6.5.x compatible

**Comment by ixti** [comment]
Released v1.0.1 that allows using sidekiq-throttled with sidekiq-6.5.x

**Comment by ixti** [comment]
Notice, though, that `sidekiq-pauzer >= 4.0.0` (required for bringing back queues pausing feature) is compatible with Sidekiq-7.x only. So You can:

1. upgrade to:
   ``` ruby
   gem "sidekiq", "< 8"
   gem "sidekiq-throttled", ">= 1"
   ```
2. once you're ready for sidekiq 7.x (my recent upgrade in a production app proved there's no problems if you're not heavily using internals or Sidekiq.redis):
   ``` ruby
   gem "sidekiq", "< 8"
   gem "sidekiq-throttled", ">= 1"
   gem "sidekiq-pauzer", ">= 4"
   ```

**Comment by skyeagle** [comment]
Excellent, thank you for the blazing-fast fix!
