### ISSUE TITLE
Multiple threshold rules

### ISSUE THREAD

**Issue by timurkhafizov** [ixti/sidekiq-throttled#17]
Hello!

Is there ability to setup multiple threshold rules for the worker?
When I try to call `sidekiq_throttle` twice then I get `Duplicate strategy name` warning.

Basically I tried this:

```
sidekiq_throttle threshold: { limit: 100, period: 1.hour }
sidekiq_throttle threshold: { limit: 3, period: 1.minute }
```

**Comment by ixti** [comment]
There's no such option at the moment.
It might become possible in the future.

**Comment by Systho** [comment]
I think this issue can be closed

**Comment by ixti** [comment]
This is available in master. Thanks to @holyketzer

**Comment by stingray665** [comment]
Either the README is wrong or this doesn't work... `TypeError (no implicit conversion of Array into Hash)`.

I tried a clean example, literally copying the sample code.

**Comment by ixti** [comment]
@stingray665 it's in the master, but not yet released. You can use for now:

``` ruby
gem "sidekiq-throttled", :git => "https://github.com/sensortower/sidekiq-throttled.git"
```

Or wait a bit, I will cut a release this weekend (forgot to do it earlier).

**Comment by stingray665** [comment]
No worries, thanks - I figured that out once I saw the StrategyCollection class was missing, left a note in the pull request issue. Working great now.
