### ISSUE TITLE
Add a concurrency per user, but also total concurrency as a whole

### ISSUE THREAD

**Issue by princejoseph** [ixti/sidekiq-throttled#190]
This is a question more, but cant apply the label

Trying to do maximum 1 job per user concurrently but also maximum of 10 jobs concurrently

```
sidekiq_throttle(
    # Allow maximum 10 concurrent jobs per project at a time and maximum 1 job per user
    concurrency: [
      { limit: 1, key_suffix: -> (user_id) { user_id } },
      { limit: 10 }
    ]
```

**Comment by mnovelo** [comment]
Are you asking whether that's correct? I think it'll work fine if you're ok with your suffix essentially being `":#{*user_id}"` which for `user_id = 1` would be `:[1]` [according to this line](https://github.com/ixti/sidekiq-throttled/blob/26aa0582cff321a521169bd2157c63afffbc126e/lib/sidekiq/throttled/strategy/base.rb#L17)

**Comment by princejoseph** [comment]
> according to this line

yes, was more thinking if the functionality works for both scenarios (like 1 job per user but max total 10 irrespective of the user). I tested it manually and it does work

**Comment by mnovelo** [comment]
We've done something similar successfully in production

**Comment by princejoseph** [comment]
Closing this as it does work when I tested it. Thank you @mnovelo
