### ISSUE TITLE
Specify key to limit on

### ISSUE THREAD

**Issue by jnylen** [ixti/sidekiq-throttled#2]
Hi!
Is it possible for you to look into a way to specify what key to throttle it on?

At the moment i'm using Sidekiq-throttler which does it via:
sidekiq_options throttle: { threshold: 20, period: 1.minute, key: 'tvdb' }

**Comment by ixti** [comment]
There's a way to create "shared" strategies:

``` ruby
# config/initializers/sidekiq-throttled.rb
Sidekiq::Throttled::Registry.add(:tvdb, {
  :threshold => { :limit => 20, :period => 1.minute }
})

# app/jobs/latest_updates_worker.rb
class LatestUpdatesWorker
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker

  sidekiq_throttle_as :tvdb

  # ...
end
```

**Comment by badlamer** [comment]
And ability to be a key lambda from job args

**Comment by ixti** [comment]
Dynamic configuration (key/limit/period) is not available ATM.
But I'm pretty open to add it.

**Comment by ixti** [comment]
I have created separate issue ( #4 ) to discuss dynamic options.
I dislike the way they are usually done, so wanna try to find the best approach.
Feel free to express your thoughts! :D

**Comment by jnylen** [comment]
As it's already a way to specific keys. Then I guess my question got answered. Thanks!
