### ISSUE TITLE
Retry Queue

### ISSUE THREAD

**Issue by benhutton** [ixti/sidekiq-throttled#20]
Is this code meant to work still once a job makes it into the sidekiq retry queue? Best I can tell, it is _not_ working, but I wanted to ask so I know whether to keep hunting for a bug in my app.

**Comment by ixti** [comment]
I'm not quiet understand. Can you please explain a bit more?

**Comment by benhutton** [comment]
@ixti sure

Say I have a sidekiq job configured with the default retry strategy. That job fails and drops into the retry queue. Is that job, in the retry queue, going to get throttled in the same way that it would in its normal queue?

**Comment by ixti** [comment]
@benhutton sorry for delay with response. It will be throttled same way it does from normal queue. If it's not then it's a bug, either in your code or in sidekiq-throttled :D

If I will find time this week - I'll add specs for this case. But if you will provide them before - it will be very highly appreciated ;)) And if it will prove bug in sidekiq-throttled I will fix it same day :D
