### ISSUE TITLE
disappearing jobs - known issue with extensions?

### ISSUE THREAD

**Issue by dbenjamin57** [ixti/sidekiq-throttled#25]
Hi there, we have encountered an issue that some jobs dont get executed even though they get enqueued(we see them in the enqueued tab in sidekiq web ui). We can't really replicate as this happens once every 1K jobs or more but its hitting us with integration testing.

Today we are using these 3 in conjuction:
gem 'sidetiq'
gem 'sidekiq-unique-jobs'
gem 'sidekiq-throttled'

Are there any known issues we should be aware of? The specific disspearing jobs we have noticed are only using 2 gems though:

class SomeWorker
include Sidekiq::Worker
include Sidekiq::Throttled::Worker

sidekiq_options unique: :until_and_while_executing
sidekiq_throttle({ concurrency: { limit: 30 } })
end

Any ideas?

**Comment by ixti** [comment]
I have a strong feeling it's kind of related to mixture of throttled and unique jobs. Will need to take some time investigating how unique jobs implement lock aquisition and release (when that happens).

**Comment by ixti** [comment]
After looking at unique jobs code I'm pretty sure it's due to it getting into the way of sidekiq-throttled middleware. In other words sidekiq-throttled conflicts a bit with unique-jobs.
