### ISSUE TITLE
Does not support Sidekiq 4.2? 

### ISSUE THREAD

**Issue by erated** [ixti/sidekiq-throttled#28]
Didnt see it in the supported versions

**Comment by ixti** [comment]
We did not tried it with Sidekiq 4.2 yet. There are no hard dependency - so it's possible to install with Sidekiq 4.2 if you want. I'm gonna add tests against Sidekiq 4.2 this week. Thanks for reminder.

**Comment by ixti** [comment]
Just ran tests suit against sidekiq 4.2 - no failures. So it's safe to use with sidekiq 4.2 :D

**Comment by xhocquet** [comment]
Hey @ixti - I was looking to use this package in my project and confirmed that rate limiting behavior also works on Sidekiq 4.2. Maybe you could add that to the list of supported Sidekiq versions in the docs? Thanks! 🙏🏻
