### ISSUE TITLE
Is there going to be support for sidekiq 5?

### ISSUE THREAD

**Issue by erated** [ixti/sidekiq-throttled#32]

**Comment by ixti** [comment]
It is. :D

**Comment by ixti** [comment]
sidekiq-throttled itself has no sidekiq constraints, so you can try it with latest version of sidekiq :D Automated tests pass against sidekiq 5.0.0, so I have added `5.0.0` to the list of officially supported versions.

**Comment by ixti** [comment]
If you will experience any problems - let me know.
