### ISSUE TITLE
Dynamic choosing of strategy

### ISSUE THREAD

**Issue by schovi** [ixti/sidekiq-throttled#42]
Hi,

I have app, where I use lot of different APIs with different limits. So far your gem is awesome. But my app scale to number of APIs and it is really hard to maintain many same jobs only with different strategy

```ruby
class Api1::ProcessItemJob
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker
  
  sidekiq_throttle_as :api1

  def perform(item_id)
    ProcessItem.call(item_id)
  end
end

class Api2::ProcessItemJob
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker
  
  sidekiq_throttle_as :api2

  def perform(item_id)
    ProcessItem.call(item_id)
  end
end
```

And there is like 10 APIs and few ProcessXYZJob. Actually I have 20+ job same job classes. I tried some variants with dynamic generating, including modules and so, but everything is hard to maintain or cause problems in development env and auto reload.

it would be awesome to choose strategy dynamically like:

```
class ProcessItemJob
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker
  
  sidekiq_throttle_as -> (api_name) { api_name }

  def perform(api_name, item_id)
    ProcessItem.call(item_id)
  end
end
```

I tried to dig in source code, but without any progress. I can't decode if worker has to be somehow firmly bind to strategy or not.

Any idea?

**Comment by schovi** [comment]
After some more digging I think I found working solution

```ruby
module Sidekiq
  module Throttled
    class << self
      def throttled?(message)
        message = JSON.parse message
        job = message.fetch("class") { return false }
        jid = message.fetch("jid") { return false }

        preload_constant! job

        args = message["args"]
        Registry.get(job, *args) do |strategy|
          return strategy.throttled?(jid, *args)
        end

        false
      rescue
        false
      end
    end

    class Middleware
      def call(_worker, msg, _queue)
        yield
      ensure
        args = msg["args"]

        Registry.get(msg["class"], *args) do |strategy|
          strategy.finalize!(msg["jid"], *args)
        end
      end
    end

    module Registry
      @dynamic = {}

      class << self
        def add_dynamic(job, dynamic)
          job = job.to_s
          warn "Duplicate dynamic strategy for job: #{job}" if @dynamic[job]
          @dynamic[job] = dynamic
        end
        def get(name, *args)
          name = name.to_s

          # Dynamic getting of strategy
          if dynamic = @dynamic[name]
            if args.length < dynamic.arity
              args = Array.new(dynamic.arity) { nil }.map.with_index do |_, i| args[i] end
            elsif args.length > dynamic.arity
              args = args[0...dynamic.arity]
            end

            name = dynamic.call(*args)
          end

          strategy = @strategies[name] || @aliases[name]

          return yield strategy if strategy && block_given?
          strategy
        end
      end
    end

    module Worker
      module ClassMethods
        def sidekiq_throttle_as something = nil, &block
          # Dynamic getting of strategy
          if block_given? || something.is_a?(Proc)
            strategy_select = block_given? ? block : something
            Sidekiq::Throttled::Registry.add_dynamic(self, strategy_select)
          else
            super
          end
        end
      end
    end
  end
end
```

Pretty ugly, but works for me now. Is it something mergable after some cleaning and testing?

**Comment by ixti** [comment]
In fact you can use key suffix for this purpose. In future I plan on total refactoring on the way one registers strategies to make it more "dynamic" stuff friendly and less sidekiq-coupled

**Comment by schovi** [comment]
@ixti ah. Didnt realize I can have dynamic key_suffix and other values. In my case it would look like?

```
 sidekiq_throttle({
    :concurrency => {
      :limit      => ->(server) { $servers_throttled[server][:limit] },
      :key_suffix => ->(server) { server }
    },
    :threshold   => {
      :limit      => ->(server) { $servers_throttled[server][:limit] },
      :period     => ->(server) { $servers_throttled[server][:period] },
      :key_suffix => ->(server) { server }
  })
```

**Comment by ixti** [comment]
@schovi Yup. It will look like this if your first argument of job's perform is `server`.

**Comment by schovi** [comment]
@ixti works!

**Comment by kalemi19** [comment]
Any plans on supporting dynamic strategies?

I basically want to enforce each queue (6 in total) to run only one Sidekiq worker (4 in total) at a time.

I was thinking of creating a different strategy for each queue, but the problem is how do I dynamically tell the workers which strategy to use.

I'm currently using [sidekiq-limit_fetch](https://github.com/brainopia/sidekiq-limit_fetch), but it's no longer maintained and there seems to be some race condition happening once in a while.

Thanks in advance.

**Comment by ixti** [comment]
@kalemi19 Please open a different issue with proposal. ATM I'm not sure I understand what do you mean. You can achieve dynamic limits with solution as seen here: https://github.com/sensortower/sidekiq-throttled/issues/42#issuecomment-354603986

**Comment by kalemi19** [comment]
I didn't want to open a different issue because something similar to what @schovi suggested would fix my problem.

```
class ProcessItemJob
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker
  
  sidekiq_throttle_as -> (device_id) { device_id }

  def perform(device_id, item_id)
    ProcessItem.call(item_id)
  end
end
```

Dynamic limits would work if the `key_suffix` was shared across different workers.

**Comment by ixti** [comment]
They are actually shared.

``` ruby
Sidekiq::Throttled::Registry.add(:my_shared_strategy, {
  :key_suffix  => proc { |device_id, *| device_id },
  :concurrency => { :limit => 42, :ttl => 3600 }
})

class ProcessItemJob
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker

  sidekiq_throttle_as :my_shared_strategy

  # ...
end


class ProcessOtherItemJob
  include Sidekiq::Worker
  include Sidekiq::Throttled::Worker

  sidekiq_throttle_as :my_shared_strategy

  # ...
end
```

**Comment by kalemi19** [comment]
Oh, I didn't know that. You may want to talk more about shared throttling strategies in the README file.

I just gave it a shot and it's working like a charm!

Thank you so much for your help and this awesome gem.

Happy New Year!
