### ISSUE TITLE
throttled web ui is empty

### ISSUE THREAD

**Issue by charlesemarsh** [ixti/sidekiq-throttled#46]
Hello all, 

Sorry if I'm missing something here... but my web ui is always empty, do I need to log myself to this area? or enable something maybe?

I'm running sidekiq (5.1.1) & sidekiq-throttled (0.8.2)

<img width="1455" alt="screen shot 2018-03-12 at 19 51 49" src="https://user-images.githubusercontent.com/732995/37306292-26c1cfe0-262f-11e8-95dd-18486b1c6487.png">

**Comment by ixti** [comment]
If you are running it with rails, you might need to eager load jobs in development environment.

**Comment by charlesemarsh** [comment]
Thanks very much! I'm not desperate for it in development mode really... was just testing, thanks again

**Comment by ixti** [comment]
So, just to explain. That tab shows "known" throttling rules. If jobs were not loaded - it won't know of them. :D

**Comment by danielgomezrico** [comment]
@ixti what do you mean by "known" throttling rules?

**Comment by ixti** [comment]
@danielgomezrico If code was not required/loaded, `sidekiq_throttle` line, naturally, will not be evaluated, so that rule will NOT be shown in UI. Files (by default) are lazy-loaded in development environment of Rails.

**Comment by danielgomezrico** [comment]
@ixti ok, thanks for answering.

**Comment by swordfish444** [comment]
@danielgomezrico @ixti We're experiencing the same issue in all environments (development and production). 

Here is what our throttles look like:

```ruby
Sidekiq::Throttled::Registry.add(:DefaultThrottle, {
  threshold: {
    limit: Rails.application.config.sidekiq_jobs_per_minute_per_org,
    key_suffix: -> (*args) { "organization:#{args[0]}" },
    period: 1.minute
  }
})

Sidekiq::Throttled::Registry.add(:EventThrottle, {
  threshold: {
    limit: Rails.application.config.sidekiq_events_per_minute_per_org,
    key_suffix: -> (*args) { "organization:#{args[0]}" },
    period: 1.minute
  }
})

Sidekiq::Throttled::Registry.add(:BatchThrottle, {
  threshold: {
    limit: Rails.application.config.sidekiq_batch_jobs_per_minute_per_org,
    key_suffix: -> (*args) { "organization:#{args[0]}" },
    period: 1.minute
  }
})
```

These throttles are attached to Sidekiq workers depending on the queue. Batch jobs process in the **batch** queue with the BatchThrottle, whereas Event jobs process in the **events** queue with the EventThrottle.

Throttles are working as expected, however, the UI is forever "empty".

![image](https://user-images.githubusercontent.com/3893966/66082647-6c959500-e51f-11e9-9bae-f2f2c825c498.png)

```sh
 rails (5.1.6)
 sidekiq-throttled (0.10.0)
 sidekiq (= 5.2.7)
```

This is an important feature to have working and any advice would be greatly appreciated!
