### ISSUE TITLE
Sidekiq::Throttled::Web.enhance_queues_tab not working in sidekiq-pro V4.0.3

### ISSUE THREAD

**Issue by Blokh** [ixti/sidekiq-throttled#48]
Greetings,

The enhance_queues_tab provides you the feature of pausing the queue.
I've noticed the feature stopped working after I updated the  sidekiq version.
It's probably the pool's logic since it became concurrent. and the pause does not block it for some reason.

gemfile.lock changed from:
 sidekiq-pro (4.0.2)
to: 
sidekiq-pro (4.0.3)
      concurrent-ruby (>= 1.0.5)

Thanks in advance,
Daniel.

**Comment by ixti** [comment]
Hm. In fact queue pausing should not be affected by sidekiq-pro update, unless you use some fetch logic provided by sidekiq-pro iteself. If you do - you will need to override their fetcher to utilize queue filter:

``` ruby
Sidekiq::Throttled::QueuesPauser.instance.filter(queues)
```

**Comment by ixti** [comment]
I never seen sidekiq-pro source code so I can't actually help in this particular case. But I think it should be pretty trivial to achieve.

**Comment by Blokh** [comment]
Thank you for the quick response, will try this ASAP and will let you know if this helped.
