### ISSUE TITLE
2 workers in 2 different queues - sharing the same key_suffix doesnt work

### ISSUE THREAD

**Issue by dbenjamin57** [ixti/sidekiq-throttled#50]
Hey, we have 2 different workers that should be throttled via the same key-suffix (contacting the same end service). 

They run in different queues as one type of action is prioritised over a different type of action (so queues have different weights). 

While they share the same key-suffix, it doesnt seem to work. That means, we are getting double the required concurrency:
E.g. Say our desired max concurrency for both workers was 10. We configured the same concurrency limit with the same suffix in both workers, and now we have 20 concurrent workers. 

Any idea how to get them to play nice?

**Comment by ixti** [comment]
Can you please provide a simple example - bsically just want to see `sidekiq_options` and `sidekiq_throttle` options.

**Comment by erated** [comment]
class Worker A
sidekiq_throttle({ concurrency: { limit: 10 },  key_suffix: 'some_lock' })
sidekiq_options queue: :queue_a
end

class Worker B
sidekiq_throttle({ concurrency: { limit: 10 },  key_suffix: 'some_lock' })
sidekiq_options queue: :queue_b
end

**Comment by ixti** [comment]
This configuration will make overall concurrency of 20. If you want  two workers to share configuration you need shared strategy for them:

``` ruby
# somewhere in initialization

Sidekiq::Throttled::Registry.add(:some_throttling_strategy, {
 :concurrency => { :limit => 10 }
})

# in workers

class WorkerA
  sidekiq_throttle_as :some_throttling_startegy
  # ...
end

class WorkerB
  sidekiq_throttle_as :some_throttling_startegy
  # ...
end
```

**Comment by erated** [comment]
Any place I can read about what is Registry? I havent found any documentation about this. 
And in our case, should the  strategy should look like the code below?

```
Sidekiq::Throttled::Registry.add(:some_throttling_strategy, {
 :concurrency => { :limit => 10 }, :key_suffix => 'some_lock' 
})
```

**Comment by ixti** [comment]
Mm... Documentation is something this gem definitely lack of. :D I guess the only place where Registry is mentioned is in API docs of [sidekiq_throttle_as](https://github.com/sensortower/sidekiq-throttled/blob/master/lib/sidekiq/throttled/worker.rb#L80-L124) method. And, some API docs of Registry.

If you need `:key_suffix` then yes, you should pass it too. So basically, second argument of `Regisrty.add` is same as what you pass to `sidekiq_throttle`.

**Comment by erated** [comment]
Works. Thanks @ixti
