### ISSUE TITLE
Concurrency 1 only maintened 15 minutes

### ISSUE THREAD

**Issue by KevinBerthier** [ixti/sidekiq-throttled#51]
A throttling strategy is set to concurrency 1

```ruby
Sidekiq::Throttled::Registry.add(:big_parser, concurrency: { limit: 1 })
```

With multiples workers using this strategy 

```ruby
class UpdateCatalogDailyWorker
  include Sidekiq::Worker
  sidekiq_options backtrace: 4, retry: false
  include Sidekiq::Throttled::Worker
  sidekiq_throttle_as :big_parser

  def perform
  end
end
```

When I run many jobs the no-concurrency is maintained only for 15 min

**Comment by ixti** [comment]
default lock ttl is 15 minutes. Increase it to be bigger than your jobs are taking:

``` ruby
Sidekiq::Throttled::Registry.add(:big_parser, concurrency: { limit: 1, ttl: 1.hour.to_i })
```

**Comment by erated** [comment]
hey Ixti, from what I noticed, even once the job is done, it will not pull in another job until the ttl is done. Is there a way to lock for either: job is done or 1 hour (whatever is shorter)?

**Comment by ixti** [comment]
@erated Are you sure you are referring to concurrency throttling? As what you describe is a behaviour of threshold throttling.

**Comment by ziaulrehman40** [comment]
@ixti I found this after 2 days of googling and stuff. Please have it somewhere in readme. Thanks

**Comment by kjvarga** [comment]
This is vital information.  Found it after noticing my production jobs were not respecting concurrency.  +1 to add to the README.

**Comment by ixti** [comment]
@kjvarga totally open for PRs on improving documentation
