### ISSUE TITLE
What is the behavior of concurrency locks around restarts?

### ISSUE THREAD

**Issue by maxshortzp** [ixti/sidekiq-throttled#61]
Hi, 

We're considering using this gem to enforce concurrency limits. I'm trying to understand the behavior of these limits on jobs that have to be "hard shutdown" during a restart.

### Question: Do locks from killed processes remain until the lock's expiration?
My understanding is that jobs that are killed without finishing on their own (and thus not hitting the middleware) will continue to be "locked" and count against the concurrency limit until their TTL expires. Is that correct?

### Example Scenario:

We restart our sidekiq processes with a 20 second shutdown grace period.
A long-running job does not finish during the grace period. So, the job's worker is hard-killed by sidekiq and the whole process shuts down shortly after.
In this case, would the job id that the process was running still remain in the set of locked jobs?

**Comment by ixti** [comment]
Yes. If clean-up middleware was not triggered (e.g. in case when worker was hard-killed then concurrency lock will be hold until expiration (15 mins by default).

**Comment by maxshortzp** [comment]
Thanks for the quick response. I don't need any further information.

Should I close this out?

**Comment by ixti** [comment]
Sure. One note though - it's possible to reset locks from sidekiq web ui.
