### ISSUE TITLE
RSpec testing

### ISSUE THREAD

**Issue by samacs** [ixti/sidekiq-throttled#62]
Hi you all,

I have a worker which is expected to be throttled dynamically. I'm trying to assert that the worker is throttled once the limit has been reached.

The `proc` that defines the concurrency limit is something along these lines:

```ruby
# Limits.rb
LIMITS = {
  'example1' => 2,
  'example2' => 1
}

class << self
  def limit(example)
    LIMITS[example.underscore]
  end
end

# Worker.rb
sidekiq_throttle concurrency: {
  limit: ->(example) { Limits.limit(example) }
}
```
Now, for the specs I have something as follows:
```ruby
Limits.LIMITS.each do |example, limit|
  let(:params) { example }
  let(:registry) { Sidekiq::Throttled::Registry }
  let(:strategy) { registry.get(described_class.to_s) }

  context 'when the concurrency limit is reached' do
    it 'should be throttled' do
      Sidekiq::Testing.fake! do
        (limit + 1).each do
          described_class.perform_async(params)
        end
        jid = described_class.perform_async(params)
        expect(strategy.throttled?(jid, params)).to be_truthy
      end
    end
  end
end
```
Now, the issue is that I'm getting intermittent specs passing, sometimes it does, sometimes it doesn't. My question is: is there any example on testing I can go to in order to simulate these scenarios?

Thanks in advance!

**Comment by ixti** [comment]
I don't see how this can ever pass. There are couple of things to keep in mind:

1. sidekiq-throttled uses redis for it's locks, thus you need to clear redis db prior examples.
2. strategy is involved when job is fetched from the redis, thus neither `inline` nor `fake` modes will behave correctly.
3. by calling `strategy.throttled?(...)` you're testing sidekiq-throttled rather than your code.

**Comment by samacs** [comment]
@ixti thanks for answering!

So, the only way for testing that this is working correctly is to expect the worker's `perform` method to not be invoked?

**Comment by samacs** [comment]
Well, apparently, one way to confirm that the concurrency limits would work as expected is to verify that the call to the `limit` proc will return the expected value and to assert that the concurrency strategy is dynamic, right?

```ruby
let(:strategy) { registry.get(described_class.to_s) }

Limit.LIMITS.each do |example, limit|
  let(:params) { example }

  it 'should limit the number of concurrent jobs' do
    expect(strategy.concurrency).to be_dynamic
    expect(strategy.concurrency.limit([params])).to eq limit
  end
end
```

**Comment by ixti** [comment]
Yes, the above looks correct to me.

**Comment by samacs** [comment]
Thanks, @ixti for your comments.
