### ISSUE TITLE
Is Sidekiq 6.0 supported?

### ISSUE THREAD

**Issue by dbackeus** [ixti/sidekiq-throttled#64]
The new Sidekiq 6.0 release is not included in your supported versions list (https://github.com/sensortower/sidekiq-throttled#supported-sidekiq-versions).

Could you confirm if Sidekiq 6.0 is supported?

If it is it would be nice to update the README to reflect this :)

**Comment by ixti** [comment]
Yes. It should be supported. Fixed. Thank you.
