### ISSUE TITLE
Are jobs throttled per worker per argument

### ISSUE THREAD

**Issue by lloydwatkin** [ixti/sidekiq-throttled#70]
For example with setup like:

```ruby
    sidekiq_throttle(
      concurrency: { limit: 5 },
    )
```

Is:
```ruby
SomeWorker.perform_later(10)
```
Throttled separately to:
```ruby
SomeWorker.perform_later(12)
```
?

And, if so, how do I ignore the arguments :)

Thanks!

**Comment by ixti** [comment]
No, by default jobs are throttled per job class, i.e. arguments are ignored.
