### ISSUE TITLE
Ruby 2.7 deprecations

### ISSUE THREAD

**Issue by nickpellant** [ixti/sidekiq-throttled#72]
**Bug description**

`sidekiq-throttled` causes deprecation warnings when used with Ruby 2.7.

**To Reproduce**

* Use `sidekiq-throttled` with Ruby 2.7
* See warnings in logs

**Examples**

> .../ruby/2.7.0/lib/ruby/gems/2.7.0/gems/sidekiq-throttled-0.11.0/lib/sidekiq/throttled/strategy.rb:89: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

> .../ruby/2.7.0/lib/ruby/gems/2.7.0/gems/sidekiq-throttled-0.11.0/lib/sidekiq/throttled/strategy/threshold.rb:41: warning: The called method `initialize' is defined here

**Proposed solution**

Fix deprecations in place; should be pretty straight forward. I'm happy to put a PR in for this when I get time.

**Comment by ixti** [comment]
:+1:
