### ISSUE TITLE
Suggestion: add Github topics to this repo

### ISSUE THREAD

**Issue by agius** [ixti/sidekiq-throttled#73]
I was looking for something like this - glad I found this gem before I tried to code my own! 😹 The first place I looked was [the Github Topic for Sidekiq](https://github.com/topics/sidekiq), but I didn't see this listed. The [ruby-toolbox page for this gem](https://www.ruby-toolbox.com/projects/sidekiq-throttled) looks like it might be pointed to an old repo, and isn't categorized. It also doesn't appear on the first page of results in [libraries.io](https://libraries.io/search?languages=Ruby&q=sidekiq&sort=rank) , which is surprising considering this looks well-maintained. I eventually found this by [searching Rubygems.org](https://rubygems.org/search?utf8=%E2%9C%93&query=sidekiq), but that's usually a last resort for me.

I think adding tags to the Github repo and getting on the Sidekiq topic page would improve discoverability, and help more Ruby devs find the right tool for the job 😸

Just a suggestion, feel free to close if irrelevant. Thanks!

**Comment by ixti** [comment]
Added topics. Thanks for pointing this out. If you think there should be more - let me now.
