### ISSUE TITLE
ActiveJOB?

### ISSUE THREAD

**Issue by jnylen** [ixti/sidekiq-throttled#8]
How to use in ActiveJob?

**Comment by ixti** [comment]
That's a good question. Unfortunately I'm not sure how. :D
From a firsts glance I was not able to figure out how to hook into ActiveJob.
Most likely we will need to prepare some kind of a shim to enhance ActiveJob with throttler when adapter is sidekiq.

**Comment by ixti** [comment]
I have a feeling that it's pretty impossible due to lots of abstractions of active job.
The only way I see how it will be possible to achieve is to extract throttler part of this gem (which I'm considering anyway) into a standalone gem and writing specialized active job extension using it.

**Comment by Shwetakale** [comment]
@ixti I am facing issues with active job and this gem. Did you created standalone gem with active job which I can look into?

**Comment by ixti** [comment]
@Shwetakale yeah, unfortunately this gem is not working good with ActiveJob and I had no bandwidth to work on extraction of throttling logic into something standalone yet. But still have it in my plans :D

**Comment by jnylen** [comment]
@ixti no worries. I have moved on to Elixir and RabbitMQ (task_bunny). So don't feel free to put in a lower prio :)

**Comment by ixti** [comment]
Oh, I love RabbitMQ. Sneakers (ruby) is amazing tool to use. :D
