### ISSUE TITLE
Release a new package?

### ISSUE THREAD

**Issue by mantrala** [ixti/sidekiq-throttled#82]
I'm trying to upgrade to ruby 2.7 and there are a lot of deprecation warnings from sidekiq-throttled. I see they were [merged](https://github.com/sensortower/sidekiq-throttled/issues/72) in May 2020.

I don't want to pull in the master. I was wondering if a new release is in the making?

**Comment by mantrala** [comment]
I can refer to the commit for now.

**Comment by ixti** [comment]
Thanks for the reminder. Released 0.12.0
