### ISSUE TITLE
When throttled and non-throttled worker are using the same queue both get throttled

### ISSUE THREAD

**Issue by radilr1** [ixti/sidekiq-throttled#95]
We have several workers in our default queue and one of them is throttled to one:
```ruby
sidekiq_throttle(concurrency: { limit: 1 })
```
when there are jobs queued with that worker all other workers using the default queue are waiting for this one to complete until they start processing.
We are expecting that the worker which has the limit will execute only one at a time and all others should take all other available threads

**Comment by saviogl** [comment]
@radilr1 FYI - https://github.com/sensortower/sidekiq-throttled/issues/94#issuecomment-905010752
